# Setup for local file uploading
local:
  service: Disk
  root: <%= Rails.root.join('storage') %>

# Setup for local test file uploading
test:
  service: Disk
  root: <%= Rails.root.join('tmp', 'test-storage') %>

# Setup for AWS S3 file uploading
amazon:
 service: S3
 access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
 secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
 region: <%= ENV['AWS_DEFAULT_REGION'] %>
 bucket: <%= ENV['AWS_CUSTOMER_DOCS_BUCKET'] %>
